- README.rdoc
- TODO.rdoc
- bin/annotate
- lib/annotate/annotate_models.rb
- lib/annotate/annotate_routes.rb
- spec/annotate/annotate_models_spec.rb
Adds 'top' and 'bottom' positions as synonyms for 'before' and 'after', respectively.
> Add top and bottom positions

- lib/tasks/migrate.rake
Reverts ctran/annotate_models#249
> Revert "Runs annotate on 'rake db:rollback' too"

- lib/tasks/migrate.rake
Yeah, this looks better. I branched from the newest develop branch so there are no conflicts now.
> Runs annotate on 'rake db:rollback' too

- lib/annotate/annotate_models.rb
- spec/annotate/annotate_models_spec.rb
> Remove new line before annotation wrapper closing statement

- README.rdoc
the docs for auto-annotating were kind of buried inside the Rails Config section, so I extended them and added a reference to them inside the Usage section
> more documentation for auto-annotate and rake tasks

- lib/annotate.rb
As the title says - this PR fixes `--w` option.
Together with my previous PR ( #283 ) it solves the Issue #267
> Make --w option work

- lib/annotate.rb
- lib/annotate/annotate_models.rb
> Ruby Wanings

- lib/annotate/annotate_models.rb
Hi,
I added the active admin models folder.
Regards!
> Added Active admin models.

- Gemfile
- README.rdoc
- spec/annotate_spec.rb
- spec/spec_helper.rb
Hi I added coveralls gem.
Now travis notifies to coveralls with the coverage.
Regards.
> Added coveralls.

- lib/annotate/annotate_models.rb
> Allow classified sorting without an ID column

- .travis.yml
- spec/spec_helper.rb
Hi, 
I moved Rubocop to the CI, it's better not runs Rubocop in the tests.
The best will be run in two pipelines.
Regards.
> Moved rubocop to outside.

- .overcommit.yml
- Gemfile
Hi,
I added overcommit gem to pass the test locally.
- Rubocop in commits.
- RSpec in pushes.
Regards.
> Added overcommit gem.

- spec/integration/rails_4.2.0/app/models/sub1/no_namespace.rb
- spec/integration/rails_4.2.0/db/migrate/20140705000020_create_no_namespaces.rb
This is the setup that should trigger #413.
Since I don't use RVM and a lot of tests seem to depend on it, let's get Travis going! 😄
> add spec for #413

- README.rdoc
- lib/annotate.rb
I think this makes it clearer about what we are actually setting with the environment variable.
> Use ANNOTATE_SKIP_ON_DB_MIGRATE ENV variable

- README.rdoc
https://github.com/thoughtbot/factory_bot/blob/master/NAME.md
> Update README, FactoryGirl -> FactoryBot

- CHANGELOG.rdoc
Add missed-opening parentheses.
> Add opening parentheses in CHANGELOG.doc

- lib/annotate/annotate_routes.rb
I removed invalid document of AnnotateRoutes.rewrite_contents.
I will add valid documents in YARD format in another PR.
> Remove invalid document of AnnotateRoutes.rewrite_contents

- spec/lib/annotate/annotate_models_spec.rb
I fixed typo commented in #726.
> Refactor RSpec for AnnotateModels (2) - Fix typos

- README.md
Fix README.md that was not updated in #724.
> Fix README for YARD format

- spec/lib/annotate/annotate_routes_spec.rb
I refactored RSpec file for another large scale refactor in another PR.
> Refactor RSpec for AnnotateRoutes (1)

- .github/workflows/release-drafter.yml
Automate release notes with https://github.com/marketplace/actions/release-drafter
> Automate release notes with release-drafter.yml
