ctran/annotate_models

- README.rdoc
- bin/annotate
- lib/annotate/annotate_models.rb
- lib/tasks/annotate_models.rake
- spec/annotate/annotate_models_spec.rb
Makes it possible to wrap annotations, as suggested in #192
> Comments wrapping

- lib/annotate/annotate_models.rb
We need to make sure a file exists before trying to require it.  Fixes #200.
> Don't crash on inherited models in subdirectories.

- bin/annotate
- lib/annotate.rb
- lib/annotate/annotate_models.rb
- lib/tasks/annotate_models.rake
Example:
#
#
#
#
#
I think it's much easier to work in that way. The option is --classified-sort.
> Add option for classified annotation (id first, timestamps/assotiactions last)

- lib/annotate.rb
when using annotate from the command line with rails 4.2.0 and ruby 2.1.3, nothing was happening.
When using annotate with the --model-dir param, it did.
Looks like the defaulting of the model-dir to 'app/models' failed because of the test on whether its nil/empty
> options[:model_dir] seems to be an array now

- README.rdoc
- bin/annotate
- lib/annotate.rb
- lib/annotate/annotate_models.rb
- lib/generators/annotate/templates/auto_annotate_models.rake
- spec/annotate/annotate_models_spec.rb
- spec/integration/rails_4.1.1/lib/tasks/auto_annotate_models.rake
- spec/integration/rails_4.2.0/lib/tasks/auto_annotate_models.rake
This adds support for foreign key annotations as requested in issue #236 .
I tried to follow the pattern used for index annotation, so it's enabled by default, and adds an additional section below the column definitions.
There's an example of the format in the spec: https://github.com/subakva/annotate_models/blob/features/foreign_key_annotations/spec/annotate/annotate_models_spec.rb#L160
> Adds support for foreign key annotations

- lib/annotate/annotate_models.rb
Potentially addresses issue# #167
Annotate_model_file is called automatically on all files in models directory and does not check if model contains SkipSchemaAnnotations tag.
> Check if model has skip tag in annotate_model_file

- lib/annotate/annotate_models.rb
- spec/annotate/annotate_models_spec.rb
We have columns of type `point` in our PostgreSQL database:
```
#<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0x007ffd7b829aa8
@coder=nil,
@default=nil,
@limit=nil,
@name="point",
@null=false,
@precision=nil,
@primary=false,
@scale=nil,
@sql_type="point",
@type=:string>
```
http://www.postgresql.org/docs/9.4/interactive/datatype-geometric.html
They are annotated as `string` in our models. This is misleading: `point` is actually 2 floats; not even close to a string.
I thought that SQL type should take precedence.
I understand that this change may be not enough or is completely wrong, and would welcome suggestions on the best solution.
> Prefer SQL column type over normalized AR type

- lib/annotate.rb
- lib/tasks/migrate.rake
> Invoke get options task before annotating migrations

- lib/annotate/annotate_models.rb
- spec/annotate/annotate_models_spec.rb
This is a fix for https://github.com/ctran/annotate_models/issues/228
The gem was trying to annotate a fixture living at filepath ```'test/fixtures/parent_children.yml'```.
Rails generates nested models as such: ```'test/fixtures/parent/children.yml'```
The fix correctly targets fixtures created for nested models. I've added unit tests for the bug and for some existing functionality.
> Annotate fixtures for nested models

- lib/annotate/annotate_models.rb
- spec/annotate/annotate_models_spec.rb
Previously, quoting an array fell back to `inspect`, which is ok for
strings, but not good for BigDecimals, for instance.
> Quote each value in default arrays

- lib/tasks/migrate.rake
This adds the feature discussed in Issue #75 
My editor strips trailing whitespace and I can fix and resubmit if that's a problem.
> Runs annotate on 'rake db:rollback' too

- lib/annotate.rb
- lib/generators/annotate/templates/auto_annotate_models.rake
- spec/annotate/annotate_models_spec.rb
This PR allows setting default `wrapper_start` and `wrapper_end` options for rake task.
I didn't include `wrapper` option here. While it's useful as a shorthand when setting options directly from the command line, I think it might be unnecessarily confusing here. If you don't agree, I can include it in the rake task as well.
PR fixes issue #266
> Accept wrapper default params

- annotate.gemspec
- lib/annotate.rb
- lib/annotate/annotate_models.rb
- lib/generators/annotate/templates/auto_annotate_models.rake
- lib/tasks/annotate_models.rake
----------
Related to #286:
----------
a scaffold generates files in the following rspec subdirectories:
+ `spec/models`
+ `spec/controllers`
+ `spec/requests`
+ `spec/routing`
currently, only `spec/models` is annotated. is there a way to annotate the other three?
> Annotate non-model test files: #286

- lib/annotate/annotate_models.rb
- lib/tasks/annotate_models.rake
* Consider ignore_columns config option when evailable
* Don't modify the original klass.columns array
** We are doing .reject! later
> Fix: Ignore columns not respected when the rake task is invoked

- bin/annotate
- lib/annotate.rb
- lib/annotate/annotate_models.rb
- lib/generators/annotate/templates/auto_annotate_models.rake
- lib/tasks/annotate_models.rake
---------------
Annotations for models in subdirectories of engines/subtrees/etc #291
---------------
I believe this is similar to the following issues: #190, #131, #88
To get it to work on my project, I have the following 2 lines in auto_annotate_models.rake:
```
'model_dir'            => ["app/models", "lib/subtree/app/models"],
'root_dir'             => ["/", "lib/subtree"],
```
> Add root_dir capability for multiple roots

- lib/tasks/migrate.rake
----------
Related to issue: #190 
+ Error is for non-mountable engines
+ Previous workaround was running `annotate` in the `spec/dummy` subdirectory (i.e. not having annotate run after every `db:migrate`)
----------
```
❯❯❯❯ rake db:migrate                                                                                                
rake aborted!
Don't know how to build task 'annotate_models'
/.../gems/annotate-2.6.7/lib/tasks/migrate.rake:29:in `update_annotations'
```
> Correctly find annotate_models task in an unmounted engine

- lib/annotate.rb
- lib/annotate/annotate_models.rb
- lib/generators/annotate/templates/auto_annotate_models.rake
- lib/tasks/annotate_models.rake
When using the `auto_annotate_models` task, the `ignore_columns` option was always set to `""`, which caused `AnnotateModels.do_annotations` to ignore all columns.
> Fix :ignore_columns option in "auto_annotate_models" task

- lib/annotate.rb
- lib/annotate/annotate_models.rb
- lib/generators/annotate/templates/auto_annotate_models.rake
- lib/tasks/annotate_models.rake
I thought it might be useful to add annotations to helpers and controllers.
The next question is do we allow everything that can be generated to be annotated?
-------
This includes:
+ javascript assets
+ stylesheet assets
+ migrations themselves
+ [js/html/json] . erb/jbuilder files for
* index
* show
* edit
* _form
> Annotate controllers and helpers

- lib/annotate/annotate_models.rb
- spec/annotate/annotate_models_spec.rb
My attempt to support Ruby 2.3 magic comments
> Ruby 2.3 magic comments support

- .travis.yml
[Ruby 2.3.0](https://www.ruby-lang.org/en/news/2015/12/25/ruby-2-3-0-released/) has been released.
> Run tests by Ruby 2.3.0

- bin/annotate
- lib/annotate.rb
- lib/annotate/annotate_routes.rb
- lib/generators/annotate/templates/auto_annotate_models.rake
- lib/tasks/annotate_models.rake
- lib/tasks/annotate_routes.rake
I use to skip routes which generate an annotation which includes local path e.g.,
````
````
which causes a file change after every annotate run - leading to bad churn on codeclimate
add `ignore_routes: "#<"` to config options to skip such routes
> Add ignore_routes option

- bin/annotate
- lib/annotate.rb
- lib/annotate/annotate_routes.rb
- lib/generators/annotate/templates/auto_annotate_models.rake
- lib/tasks/annotate_models.rake
- lib/tasks/annotate_routes.rake
Reverts ctran/annotate_models#312
> Revert "Add ignore_routes option"

- README.rdoc
RDoc supports +code+ syntax only for words, not phrases. That's why several commands in Readme are not rendered correctly. This PR fixes the issue by using <code> tag there.
> fix code markup in docs

- bin/annotate
- lib/annotate.rb
- lib/annotate/annotate_routes.rb
- lib/generators/annotate/templates/auto_annotate_models.rake
- lib/tasks/annotate_models.rake
- lib/tasks/annotate_routes.rake
I use to skip routes which generate an annotation which includes local path e.g.,
````
````
which causes a file change after every annotate run - leading to bad churn on codeclimate
add `ignore_routes: "#<"` to config options to skip such routes
> Add :ignore_routes option to skip routes which should not be annotated based on regex

- lib/tasks/annotate_models.rake
Support `hide_limit_column_types` options in annotate_models.rake.
I want to output 'integer(8)'.
> Support hide_limit_column_types options in annotate_models.rake

- lib/annotate/annotate_models.rb
- spec/annotate/annotate_models_spec.rb
This fixes issue #329 .
When removing annotations it will also remove the opening wrapper.
There are two ways it could be implemented:
* remove line before the annotation if it matches the `wrapper_open`
* remove the line before the annotation if it's a comment
I went with the first option, because I wanted to avoid the risk of removing a comment that isn't a wrapper opening. The drawback is that it will only work if the `wrapper_option` is set to the same value as it was when the annotation was created.
Let me know if you think the alternative approach would be better.
> Don't leave wrapper when removing annotations

- .rubocop_todo.yml
- Gemfile
- Rakefile
- lib/annotate/annotate_models.rb
- lib/annotate/annotate_routes.rb
- Replace SpaceAroundKeyword with SpaceAfterControlKeyword
- Use an explicit rubocop version to avoid breakages during PRs
> Fix rubocop problems due to version change

- lib/annotate/annotate_models.rb
The fatal error was introduced with commit fc31d85. The method
`supports_foreign_keys?` is only available on ActiveRecord versions
`>= 4.2`.
Fixes issue 316.
> Fix fatal error when using `annotate` with ActiveRecord 4.1

- spec/annotate/annotate_models_spec.rb
@ctran Added a unit test to cover the fix for https://github.com/ctran/annotate_models/issues/348
> Add unit tests for classified sort option

- .rubocop_todo.yml
- lib/annotate/annotate_models.rb
- spec/annotate/annotate_models_spec.rb
I find it very useful to have `on_delete` and `on_update` FK constraint values in annotations.
e.g.
`fk_rails_02e851e3b7  (foreign_thing_id => foreign_things.id) ON DELETE => nullify ON UPDATE => cascade`
in case of `-f makrdown` option:
`fk_rails_02e851e3b7 ` (_ON DELETE => nullify ON UPDATE => cascade_)
> Annotate on_delete/on_update foreign key constraints

- annotate.gemspec
This is the same as #359 but against the develop branch.
> Allow rake 11 in annotate.gemspec

- .rubocop_todo.yml
- lib/annotate/annotate_models.rb
Hi,
I have found a bug where (wenn generating with an wrapper-open and wrapper-close) the wrapper-open text stays in the document.
The wrapper-open content gets repeated even more when renewing the annotations.
transforming:
```
#
#
#--
#++
```
into:
```
#
#
#--
#++
```
in this example the `# rubocop:disable Metrics/LineLength` gets increased on every annotation change.
this pull request fixes this bug.
> fix so that the wrapper-opening does not gets duplicated

- lib/annotate/annotate_models.rb
Annotate should reset the cached information about columns because Annotate may output old information if we load `ActiveRecord::Base` class in migration files.
For example, if we have a following migration file and execute `rake db:migrate`, Annote does not output the default value and a not null constraint of the `some_value` column.
```ruby
class CreatePosts < ActiveRecord::Migration
def change
create_table :posts do |t|
t.integer :some_value
end
Post.update_all(some_value: 1)
change_column_null(:posts, :some_value, false)
change_column_default(:posts, :some_value, 1)
end
end
```
This commit fixes the above issue.
before this commit
```ruby
#
#
#
class Post < ActiveRecord::Base
end
```
after this commit
```ruby
#
#
#
class Post < ActiveRecord::Base
end
```
> Annotate should reset the cached information about columns

- .rubocop_todo.yml
- lib/annotate.rb
- lib/annotate/annotate_models.rb
- lib/generators/annotate/templates/auto_annotate_models.rake
- lib/tasks/annotate_models.rake
- spec/annotate/annotate_models_spec.rb
I've added an option named `exclude_sti_subclasses` and code which checks if a model has a superclass under AR::B with the same table in order to exclude STI subclasses from annotation. 
this is a need I have on a project with a large number of subclasses of certain models, where annotating every one generates a lot of noise on any schema change, so I prefer to just annotate the parent class.
> add option to exclude STI subclasses from annotation

- lib/annotate/annotate_models.rb
Fixes Issue #377 
Tested manually on Rails 5.0.0.rc1.  String and array indexes work with this patch.  I didn't see any existing place in the tests to add this.
> Coerce string `index.columns` to Array before join

- README.rdoc
- bin/annotate
Command line options documentation previously asked for values to be separated by "comas" not "commas."
> Fix spelling to commas

- lib/annotate/annotate_models.rb
- spec/annotate/annotate_models_spec.rb
> Do not include auto-generated foreign key names in schema dump

- lib/annotate.rb
use existence of 'Rails::Application' as indicator of Rails App instead of using 'Rails', as many Ruby applications are using railties such as generators outside Rails.
> use existence of 'Rails::Application' as indicator of Rails App

- lib/annotate/annotate_models.rb
Ruby 2.4.0 unifies Fixnum and Bignum into Integer.
https://bugs.ruby-lang.org/issues/12005
Fix following deprecated warnings in Ruby 2.4.0-preview3.
- `warning: constant ::Fixnum is deprecated`
- `warning: constant ::Bignum is deprecated`
Thanks
> Fix deprecated warnings in Ruby 2.4.0+

- circle.yml
Fixed following error when run `bundle install`.
```sh
bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 
Bundler can't satisfy your Gemfile's dependencies.
Install missing gems with `bundle install`.
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
ruby_dep-1.5.0 requires ruby version >= 2.2.5, which is incompatible with the
current version, ruby 2.2.4p230
```
cf. https://circleci.com/gh/ctran/annotate_models/257
> Test against Ruby 2.2.6 on CircleCI

- annotate.gemspec
Current Rake is v 12.0.0 and Gem won't install
> Valid for rake earlier than v 12.1

- Gemfile
- lib/annotate/annotate_models.rb
- spec/annotate/annotate_models_spec.rb
Hello,
I have a issue with my Postgresql database and the index annotations. 
In some models I added the table_name_prefix = 'public.' because I'm using different schemas and the annotation doesn't work because is looking for 'public.table_name' and doesn't exist.
Regards.
> Fixed Posgresql index tables with `public`.

- lib/tasks/annotate_models.rake
This commit https://github.com/ctran/annotate_models/commit/89d513ca535e7e34cd54747f7a818f0e5b8a0843 forgot the option to the library.
> Forgotten option hide_default_column_types

- lib/annotate/annotate_routes.rb
Apply compact to max array for filter nil values: https://github.com/ctran/annotate_models/blob/develop/lib/annotate/annotate_routes.rb#L44
> Fix bug, the max array can contains a nil values.

- .rubocop_todo.yml
- lib/annotate/annotate_models.rb
- spec/annotate/annotate_models_spec.rb
https://github.com/ctran/annotate_models/issues/380
> Do not check if an index includes another column if the name is a String, instead of an Array.

- lib/annotate.rb
- lib/annotate/annotate_models.rb
- lib/tasks/annotate_models.rake
This is a quick fix for #340.
When setting root_dir to an empty string (as is done in the default rake task config) this line previously caused root_dir to become an empty array.
This in turn caused factories, specs etc not to be annotated.
This is just a quick band-aid on a larger problem. We have option parsing spread out over many different places, with slight mismatches like this in the assumptions made.
> Prevent root_dir option from being empty

- annotate.gemspec
> Fix gemspec: rename lib/tasks{migrate => annotate_models_migrate}.rake

- annotate.gemspec
- lib/annotate/annotate_models.rb
- lib/generators/annotate/templates/auto_annotate_models.rake
- lib/tasks/annotate_models.rake
- spec/annotate/annotate_models_spec.rb
upgrading old(er) projects dependencies, including annotate, causes loads of random changes which are not of any use, spamming git history with noise. comments-only-changes.
also, upgrading rake too then causes a downgrade form 2.7 to order version, causing further noise. 
without exaggerating, i almost died because of this. twice.
always trying to keep my history clean, i made fk-truncation optional and allowing rake 12. feel free.
Sorry for the bad vibes, but, based on my perspective, this was quite a waste of time to force change into existing annotations.
To let it sparkle however, thanks for this -gem-, literally. Cheers
> Optional FK-Truncation / Rake update

- .rubocop_todo.yml
- lib/annotate/annotate_models.rb
- lib/generators/annotate/templates/auto_annotate_models.rake
- spec/annotate/annotate_models_spec.rb
#433
+ Support Database Comment for Rails5 
+ Added  with_comment options
> Support database comment for rails 5

- lib/annotate/annotate_routes.rb
Pointed out by @yhirano55 in #455, the private keyword is not valid in this context.
> Remove "private" since it's not valid in context

- lib/annotate/annotate_models.rb
LoadError is the critical one to rescue here, but it does not descend from `StandardError` so the fallback loading is never invoked.
```
>> LoadError.ancestors
=> [LoadError, ScriptError, Exception, Object, Kernel, BasicObject]
```
```
$ bundle exec annotate
D, [2017-06-02T13:02:41.484425 #16758] DEBUG -- :   ActiveRecord::SchemaMigration Load (0.2ms)  SELECT `schema_migrations`.* FROM `schema_migrations` /*application:Tophatter*/
/Users/pboling/.rvm/gems/ruby-2.2.6/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:495:in `load_missing_constant': Unable to autoload constant CsvRequest, expected /Users/pboling/Documents/tophatter/app/models/csv_request.rb to define it (LoadError)
from /Users/pboling/.rvm/gems/ruby-2.2.6/gems/activesupport-4.2.7.1/lib/active_support/dependencies. …
```
> Allow use of fallback class loading solution

- lib/annotate.rb
- spec/annotate/annotate_models_spec.rb
https://github.com/ctran/annotate_models/pull/458 introduced a `show_complete_foreign_keys` setting that defaults to `false`.  But, setting it to `true` didn't actually work, because it was excluded from `FLAG_OPTIONS`
> Fix show_complete_foreign_keys setting

- .rubocop_todo.yml
- README.rdoc
- bin/annotate
adds the show_complete_foreign_keys flag to the cli, which i forgot. see #475.
i named it `--ck` in short, to have it aligned under `-k` hence is why i also set the `show_foreign_keys` option positive.
had to increase the `Metrics/BlockLength` a bit to make rubocop pass. Since `bin/annotate` is a good candidate for even more lines, i`d recommend to keep smaller blocks and exclude the file from this check.
However, this is a entirely different discussion which is why i did the increment only.
Did not find a spec for the bin options itself. is it missing or is it just me?
also, sorry all for the wrong branch name after an creating a useless ticket, bad memory.
> #476 add missing complete-foreign-keys option to bin

- .travis.yml
- Gemfile
- annotate.gemspec
- lib/annotate/version.rb
Drop support of Ruby < 2.2 since [Support of Ruby 2.1 has ended](https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/).
> Drop support of Ruby < 2.2

- lib/annotate/annotate_models.rb
- spec/annotate/annotate_models_spec.rb
Solves #403 
Now if you have ordered indexes, order direction will be added next to the column name.
Example:
```
#
```
Markdown is also supported.
> Annotate ordered indexes

- lib/annotate/annotate_models.rb
- spec/annotate/annotate_models_spec.rb
This pull request is inspired by other PR https://github.com/ctran/annotate_models/pull/422
It adds WHERE and USING values to the index info.
This is really useful feature, and since original PR contributor does not appear since Dec 2016, I decided to push it forward. Hope this is fine.
USING is added only if index is not `btree`.
Difference from #422:
1) Markdown support
2) Refactored code
3) Added missing specs
Example:
```
#
```
> Indexes: add WHERE and USING

- lib/annotate/annotate_routes.rb
- spec/annotate/annotate_routes_spec.rb
Fixes https://github.com/ctran/annotate_models/issues/474
Actually, not only fixes issue with trailing space, but removes last empty line (`#[EOL]`) at the end of routes map completely.
Example:
Instead of
```
#
```
Now it will be
```
#
```
Here is why this empty line occurred in the first place:
`rake routes` returns text with a new line character at the very end.
`AnnotateRoutes` treated this last empty line as a useful content and added `# [EOL]` because of it.
I decided to remove `# [EOL]`, because specs show that it wasn't expected from the beginning. Specs passed only because there was an assumption that `rake routes` doesn't add new line character at the end, which is wrong.
> Remove empty line with trailing space at the end of routes map

- bin/annotate
- lib/annotate.rb
This change is a proposed solution to #357 and an alternative to the already proposed solution #361.
In #361 it is needed to call `annotate --routes --ignore-models` to achieve the same as in this change with only `annotate --routes`.
> annotate --routes modifies only routes.rb

- .travis.yml
Use latest Rubies (2.2.7 / 2.3.4 / 2.4.1) for TravisCI.
> Test against latest Rubies (2.2.7 / 2.3.4 / 2.4.1) on TravisCI

- README.rdoc
- lib/generators/annotate/install_generator.rb
I've added option `require: false` on Usage. Because this gem doesn't need autorequiring. And I've refactored tiny things. Thanks.
> Fix README

- lib/annotate/annotate_models.rb
- spec/annotate/annotate_models_spec.rb
Please see #436 for the original issue description.
> Fix #436 where extra line break is added when using windows CRLF

- lib/annotate/annotate_models.rb
- spec/annotate/annotate_models_spec.rb
> [Fix #464] Add an empty line between magic comment and schema

- lib/annotate/annotate_models.rb
In our usecase, factory_girl files be exist to nested directory of pluralize pattern.
Example:
```
app/models/admin/user.rb -> spec/factories/admin/users.rb
```
We would be happy if file patterns include to this.
(Or file pattern to be able to set by configuration)
Thanks.
> Add pluralized file patterns for factory_girl

- lib/annotate/annotate_routes.rb
- lib/tasks/annotate_routes.rake
- spec/annotate/annotate_routes_spec.rb
Please see #401
TL;DR: now you can use `wrapper_open`/`wrapper_close` options not only in models annotation, but also in routes annotation as well.
> [Fix #401] Allow wrappers in routes annotation

- lib/annotate/annotate_routes.rb
- spec/annotate/annotate_routes_spec.rb
Fixes #414 
TL;DR: `AnnotateRoutes.remove_annotations` was completely broken - it duplicated routes list instead of just removing annotations block.
> [Fix #414] Fix: AnnotateRoutes.remove_annotations duplicates routes

- lib/annotate/annotate_models.rb
- spec/annotate/annotate_models_spec.rb
The `annotate` command can accept the target model files as command line arguments:
```
Usage: annotate [options] [model_file]*
```
However, the following error occurred:
```
% bundle exec annotate app/models/author.rb
bundler: failed to load command: annotate (/Users/hideki/repos/src/local/sample/vendor/bundle/ruby/2.4.0/bin/annotate)
TypeError: no implicit conversion of nil into String
/Users/hideki/repos/src/local/sample/vendor/bundle/ruby/2.4.0/gems/annotate-2.7.2/lib/annotate/annotate_models.rb:646:in `join'
/Users/hideki/repos/src/local/sample/vendor/bundle/ruby/2.4.0/gems/annotate-2.7.2/lib/annotate/annotate_models.rb:646:in `block in do_annotations'
/Users/hideki/repos/src/local/sample/vendor/bundle/ruby/2.4.0/gems/annotate-2.7.2/lib/annotate/annotate_models.rb:645:in `each' …
```
> Fix it possible to specify model files as argument

- lib/annotate/annotate_models.rb
- spec/annotate/annotate_models_spec.rb
Bigint columns display integer in annotation. Because  `ActiveRecord::ConnectionAdapters::Column#type` returns `:integer` if its column type is bigint.
`#bigint?` is provided to distinguish them so I changed to use it.
> annotate bigint correctly

- lib/annotate/annotate_models.rb
I found that `annotate` command is failed when `table_name` of model class is frozen.
Please see the sample model class code.
```ruby
class User < ApplicationRecord
self.table_name = 'tbl_users'
end
```
When `annotate` command is executed to the model file, it is failed with following message .
(Messages with `--trace` option are [backtraces.txt](https://github.com/ctran/annotate_models/files/1376549/backtraces.txt).)
```
Unable to annotate app/models/user.rb: can't modify frozen String
Unable to annotate app/models/user.rb: no implicit conversion of nil into Array
```
This is seemed to be caused by [this line](https://github.com/ctran/annotate_models/blob/develop/lib/annotate/annotate_models.rb#L215).
`table_name.to_s.slice!(klass.table_name_prefix)` changes `table_name` string itself, …
> Fix unable to annotate error when table_name is frozen

- README.rdoc
- bin/annotate
@ctran: I've updated the README with the `--with-comment` flag, like you asked. Actually, I just ran `annotate --help` and copied the output to `README.rdoc`. 😄 I guess there are a few new things that were missing.
Also the `-aa` shortcut for the `--active-admin` flag didn't look right, so I changed it. Hope that's OK 😊
> Update CL options in README

- lib/annotate/annotate_routes.rb
- spec/annotate/annotate_routes_spec.rb
See comments at the bottom of https://github.com/ctran/annotate_models/issues/401
Added support of magic comments to `AnnotateRoutes`.
> Do not remove magic comments (AnnotateRoutes)

- README.rdoc
For this `rails g annotate:install` to work (as well as rake task), the gem should be required in rails application. Otherwise, `uninitialized constant AnnotateModels (NameError)` will be thrown.
> Update Readme Gemfile declaration

- Rakefile
- lib/annotate.rb
- lib/annotate/annotate_models.rb
- spec/annotate/annotate_models_spec.rb
- spec/integration/rails_2.3_with_bundler/config/boot.rb
We had a script that ran a Rails migration. Since its output is noisy, we swallowed stdout. The exit code was `1` but there was no message because `annotate_models` puts its error messages to stdout instead of stderr.
This PR redirects error messages to the current standard error stream `$stderr`.
**Before**
```
$ bundle exec rake annotate_models >/dev/null
$ echo $?
1
```
**After**
```
$ bundle exec rake annotate_models >/dev/null
No models found in directory 'app/models'.
Either specify models on the command line, or use the --model-dir option.
Call 'annotate --help' for more info.
$ echo $?
1
```
> Redirect error messages to current standard error stream

- lib/annotate/annotate_models.rb
If there is any newline characters in an index's expression, that piece of comment will be splitted in two lines, thus corrupting the annotated file.
This pull request fixes the issue by escaping these newline characters.
> Escape newline characters in index expression

- lib/tasks/annotate_models.rake
* :with_comment option is flag.
* It should use `true?` instead of `fallback`.
Now with_comment option is enforcely overwritten in annotate_models.rake. So I've fixed it.
> Fix with_comment format in annotate_models_rake

- lib/generators/annotate/templates/auto_annotate_models.rake
:with_comment option should use string instead of boolean as same as others.
> Use string instead of boolean

- lib/annotate/annotate_models.rb
This fixes #555, fixes #472, and possibly more.
This is currently built on top of #571, because it hits the same lines of code.  If for some reason you want to merge this one and not #571, I'll be happy to refactor.
> Keep same surrounding whitespace when re-annotating a file

- lib/annotate/annotate_models.rb
Refactor and simplify returns for `annotate_one_file`.   This simplifies some big if/else blocks that were wrapping significant portions of this method.  No logic is changed.
This is best viewed hiding whitespace changes (under the "Diff settings" button).
This is currently built on top of #573, because it hits the same lines of code (I split it out because the whitespace changes make it hit every line in the function). If for some reason you want to merge this one and not #573, I'll be happy to refactor.
> Refactor and simplify returns

- lib/annotate/annotate_models.rb
- spec/annotate/annotate_models_spec.rb
This fixes alignment of Japanese, Korean and Chinese fullwidth character comments.
The displayed widths of multi-byte fullwidth characters are generally
twice as large as the ASCII characters, but String#size returns only the number of characters.
So if the column comment contains fullwidth multibyte characters, the alignment is broken.
Monospaced font-family supporting multi-byte isn't used in GitHub diff view, you can confirm the fixed alignment with `font-family: "Osaka-mono", "MS Gothic";`.
cf. https://gyazo.com/d878a077b7494f07bcc45ecf7c0adb62
> Fix alignment of multi-byte fullwidth character comments

- lib/annotate/annotate_models.rb
- spec/annotate/annotate_models_spec.rb
When position is set to after or bottom the current behavior added an extra newline following magic comments. 
If the file is being annotated at position after/bottom there should be no need to make modifications after the magic comments. (Any style/formatting there is not the concern of this gem if the file is not being annotated there.)
This change fixes that behavior to only insert a newline if the file is being annotated at position before/top, i.e. between the magic comments and existing content.
> Do not add whitespace after magic comments when annotating at position after/bottom

- lib/tasks/annotate_models_migrate.rake
- spec/tasks/annotate_models_migrate_spec.rb
Added 3 changes:
1. Use `Rake::Task#enhance` insteaad of defining same tasks again.
2. Remove hooking `db:migrate:change` task which doesn't exist. This hook has been added by #42, but as far as I searched I can't find the task in Rails 3.1 or greater version.
3. Fix hooking `db:migrate:redo` task so that the annotation runs after all migration tasks.  Close #548.
This is done by hooking the top level task to run the annnotation. (ref: https://stackoverflow.com/a/3915951)
> Refactor hooking ActiveRecord migration tasks

- lib/tasks/annotate_models_migrate.rake
Since Rails full engines run as non-namespaced applications
but all their app-related tasks still prefixed with app:.
> Try "app:" task prefix on migration annotaiton

- lib/tasks/annotate_models.rake
Allow ignore_unknown_models to be overridden by an environment variable. This allows people to silence errors from non-AR models present in the `models` folder.
> Allow ignore_unknown_models to be overridden by an environment variable

- README.rdoc
- bin/annotate
- lib/annotate.rb
- lib/annotate/annotate_models.rb
- lib/generators/annotate/templates/auto_annotate_models.rake
- lib/tasks/annotate_models.rake
- spec/annotate/annotate_models_spec.rb
fix #317 
Add `--frozen` option to abort instead of write annotation.
This is mainly for CI environment to detect missing annotation.
Similar motivation with `bundle install --frozen`.
works like:
```
$ rake db:migrate frozen=yes
..
annotate error. spec/models/user_spec.rb needs to be updated, but annotate was run with `--frozen`.
```
> Add frozen option

- lib/annotate/annotate_routes.rb
First I tried to extend `AnnotateModels`, but I found several problems in `AnnotateModels` and `AnnotateRoutes`.
In `AnnotateRoutes`, there were many public methods that is not used in other classes or modules.
Before my extension, I made these methods private and sort them in order of appearance.
All tests were passed.
Please trace each commits carefully. I didn't nothing special. The commits consist of coordinating code.
As [Code Climate](https://codeclimate.com/github/ctran/annotate_models) shows, this gem is hard to maintain. 
So I'd like to refactor this gem in the near future.
> Make methods private in AnnotateRoutes

- lib/annotate/annotate_models.rb
- spec/annotate/annotate_models_spec.rb
> fix annotations for columns with long data types

- .travis.yml
This PR updates Ruby `2.2.X` to use `2.2.10`. It also unblocks Ruby 2.2 builds currently failing in CI. This happens because builds try updating to RubyGems 3 which does not support Ruby 2.2.
> Update .travis.yml to unblock Ruby 2.2 builds

- spec/annotate/annotate_models_spec.rb
It is as the subject.
Refer
ruby/bigdecimal@5337373
> Suppress `warning: BigDecimal.new is deprecated`

- annotate.gemspec
The RubyGems gemspec property `rubyforge_project` has been removed without a replacement.
> gemspec: drop rubyforge_project, it is EOL

- lib/annotate/parser.rb
- spec/annotate/parser_spec.rb
Refactored Parser to isolate changes being made to ENV. This way we have an intermediate step where we know the environment variables being set.
> Refactor Parser

- README.rdoc
- lib/annotate.rb
- lib/annotate/parser.rb
- lib/generators/annotate/templates/auto_annotate_models.rake
- spec/lib/annotate/parser_spec.rb
Prior to this change, `Annotate.include_models?` returned the inverse of `Annotate.include_routes?`. This made it so annotating models and routes was not possible to do together.
This PR adds an explicit `--models` flag and also adds it the option to `lib/generators/annotate/templates/auto_annotate_models.rake` with the default being set to `false`. 
Fixes #563 and undoes the bug introduced in #485.
> Make it possible to annotate models and routes together

- lib/annotate/parser.rb
make compatible with README.md
> Fix --models option description

- lib/annotate.rb
- lib/annotate/annotate_models.rb
- lib/annotate/constants.rb
- spec/lib/annotate_spec.rb
Adds tests for `.include_routes?`, `.include_models?`, `.skip_on_migration?`. Also moves the `TRUE_RE` under the `Annotate::Constants` namespace.
> Refactor and tidy lib/annotate.rb

- README.rdoc
- lib/annotate/parser.rb
- spec/lib/annotate/parser_spec.rb
Changed references to `--additional_file_patterns` to be `--additional-file-patterns` to make it consistent with other flags.
> Make --additional_file_patterns consistent by using dashes

- annotate.gemspec
Currently the gem released as version 3.0.0 is broken. Fixes #657 
The gem is missing constants.rb and parser.rb file
> Add constants.rb and parser.rb files to gemspec

- annotate.gemspec
Before, whenever a new file is added to `lib`, the contributor or maintainer has to remember to explicitly add it to the gemspec. If this step is forgotten, it results in a broken release, like #657.
This commit makes this process less error prone by using `git ls-files` to automatically include all appropriate files in the gem. This is in line with what is advocated by Bundler's gem template:
https://github.com/bundler/bundler/blob/2a4d88a7044528209321fd4441e995ec66f604b9/lib/bundler/templates/newgem/newgem.gemspec.tt#L26
To test this PR I ran `rake gem` and verified that the list of files included in the gem is the same as before:
```
AUTHORS.rdoc
CHANGELOG.rdoc
README.rdoc
RELEASE.rdoc
TODO.rdoc
annotate.gemspec
bin/annotate
lib/annotate.rb
lib/annotate/active_record_patch.rb …
```
> Use a less error-prone way of specifying gem files

- README.rdoc
Based on the official docs:
https://help.github.com/en/articles/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository
> Add GitHub Actions badge for CI workflow

- lib/generators/annotate/templates/auto_annotate_models.rake
Setting the default to annotate models as it is the main feature of the gem.
Solves #663
> Defaults annotate models to true

- .github/workflows/release.yml
Reverted tag matcher to to use `v*` prefix instead of `release/v*`.
> Revert behavior of Github release action

- .rubocop_todo.yml
- lib/annotate/annotate_models.rb
- spec/lib/annotate/annotate_models_spec.rb
> Fix shifted when format_markdown option enabled and used non-ascii

- lib/annotate/annotate_models.rb
- spec/lib/annotate/annotate_models_spec.rb
When there are already a blank line between the magic comment and the class definition, generating annotation would insert an additional blank line after itself, leaving two blank lines between itself and the class definition.
This closes #591.
> FIX: Ensure only one line is around the annotation

- lib/annotate/annotate_models.rb
- spec/lib/annotate/annotate_models_spec.rb
Fixes https://github.com/ctran/annotate_models/issues/675
> [Fix #675] Correct indentation for double-byte characters

- lib/annotate/annotate_models.rb
- spec/lib/annotate/annotate_models_spec.rb
Fixes #624 
Note: I was not able to reproduce the issue with gem enumerize (https://github.com/brainspec/enumerize), however it is reproducible with ActiveRecord::Enum.
> [Fix #624] Correct default values when ActiveRecord::Enum is used

- lib/annotate/annotate_models.rb
The current serializers test directory files assumed that the file ended in `_spec.rb` instead of `_test.rb`, that's why I wasn't getting my serializer tests annotated.
> Fix serializers test directory files

- lib/annotate/annotate_models.rb
Rails 6 has dropped name from options for ActiveRecord::ConnectionAdapters::ForeignKeyDefinition
for Sqlite3 adapter:
https://github.com/rails/rails/blob/f2df77709f7e536aaf4d6f984ff21a49d44d34c1/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb#L305-L311
This has caused issues with getting foreign key info and blowing up
when trying to annotate models with foreign keys. This commit
adds one additional check for name presence and uses column
attribute from options instead.
Closes #620.
> Fix foreign key issue with Rails 6 and Sqlite3

- lib/generators/annotate/templates/auto_annotate_models.rake
Add's the `active_admin` option to the auto annotate rake task template.
> Add ActiveAdmin option to template

- .github/workflows/ci.yml
- .travis.yml
Looks like it's breaking in Github CI because Ruby 2.3.X is no longer supported by `actions/setup-ruby@v1`. Ruby 2.3.X has stopped being supported since March of 2019, so I've removed Ruby 2.3.X versions from both Github and Travis CI.
It's also breaking in Travis CI because it's timing out in an interactive prompt when trying to do `gem update --system`. This is due to changes to [Ruby Gems 3.1.1](https://github.com/rubygems/rubygems/issues/3036). This has been fixed.
Failing Github CI build: https://github.com/ctran/annotate_models/runs/335456181
Failing Travis build: https://api.travis-ci.org/v3/job/625759725/log.txt
> Upgrade and fix CI

- .rubocop_todo.yml
- lib/annotate/annotate_models.rb
- spec/lib/annotate/annotate_models_spec.rb
Same problem returned by @janosrusiczki in #430
Spatial columns with activerecord-postgis-adapter (5.2.2) are not displayed nice
```
```
That's come from activerecord-postgis-adapter, with redefined columns as such :
``` 
#<ActiveRecord::ConnectionAdapters::PostGIS::SpatialColumn 
@sql_type="geometry(Geometry,4326)",
@geo_type="Geometry",
@geometric_type=RGeo::Feature::Geometry,
@srid=4326,
@limit={:srid=>4326, :type=>"geometry"}
[...]
>
```
This fix displays them like this :
```
```
Another possibility would have been to display them as below, but it involves a lot of extra-spaces for other columns.
```
```
> Handle columns from activerecord-postgis-adapter

- .rubocop_todo.yml
- lib/annotate/annotate_models.rb
- spec/lib/annotate/annotate_models_spec.rb
> [Fix #570] Change of foreign key should be considered as a column change

- lib/annotate.rb
`HashWithIndifferentAccess` is soft-deprecated from https://github.com/rails/rails/pull/28157 (since Rails 5.1)
But there are still no deprecation warnings, please merge if necessary :)
> Replace soft-deprecated constant `HashWithIndifferentAccess` to `ActiveSupport::HashWithIndifferentAccess`

- lib/annotate/annotate_routes.rb
Before I commited, the method `AnnotateRoutes.where_header_found` returned an array of `real_content` and `header_found_at`.
I fixed the name of method and variable because they did not match.
I renamed the method `real_content_and_header_position` and unified related variable names to `header_position`.
> Rename method and variable of AnnotateRoutes for readability

- lib/annotate/annotate_models.rb
- lib/annotate/annotate_routes.rb
I added `AnnotateModels::MAGIC_COMMENT_MATCHER` and `AnnotateRoutes::MAGIC_COMMENT_MATCHER` instad of `AnnotateModels.magic_comment_matcher` and `AnnotateRoutes.magic_comment_matcher`.
I think that they should be constants because the result of Regexp is always fixed.
> Add constants MAGIC_COMMENT_MATCHER

- lib/annotate/annotate_routes.rb
As the change log shows, I froze the constant `HEADER_ROW` in accordance with the normal Ruby style regulation.
> Freeze constant AnnotateRoutes::HEADER_ROW

- lib/annotate/annotate_routes.rb
I refactored `AnnotateRoutes.header` for performance, and add `AnnotateRoutes.comment` to make code DRY.
> Refactor AnnotateRoutes.header

- lib/annotate/annotate_models.rb
- spec/integration/rails_3.2_autoloading_factory_girl/test/factories/tasks.rb
Now the gem [factory_girl](https://github.com/thoughtbot/factory_girl) have been renamed to [factory_bot](https://github.com/thoughtbot/factory_bot).
So I fixed constant names and comments.
> Rename FactoryGirl to FactoryBot

- lib/annotate/annotate_routes.rb
I replaced `Array#map` to `Array#each` because the mapped array is not used.
> Fix AnnotateRoutes.extract_magic_comments_from_array

- lib/annotate.rb
*   Remove redundant `Annotate.loaded_tasks=` and `Annotate.loaded_tasks`
*   Remove unnecessary comment for Rubocop
*   Make Annotate.load_requires private
*   Refactor `Annotate.load_tasks`
> Refactor namespace Annotate

- lib/annotate/annotate_routes.rb
I refactored `AnnotateRoutes.remove_annotations`.
*  Build `new_text` in `.remove_annotations`
*  Add trailing new line in `.strip_on_removal`
*  Use `.rewrite_contents` for comparing `existing_text` and `new_text`, and write `new_text` to the file.
> Refactor AnnotateRoutes.remove_annotations

- lib/annotate/annotate_routes.rb
- spec/lib/annotate/annotate_routes_spec.rb
I refactored `AnnotateRoutes.routes_exists?` and methods using this.
The points are as follows.
*   Removing `puts` in `AnnotateRoutes.routes_exists?`
*   Using `File.exist?` instead of `File.exists?` because `File.exists?` is deprecated
*   Renaming `AnnotateRoutes.routes_exists?` to `AnnotateRoutes.routes_file_exists?` in order to make the name of method more explanatory
> Refactor AnnotateRoutes.routes_file_exist?

- lib/annotate/helpers.rb
I refactored two methods in AnnotateModels::Helpers for readability.
> Refactor AnnotateModels::Helpers

- spec/lib/annotate/annotate_models_spec.rb
I refactored and structuralized RSpec test cases of AnnotateModels for readability and scalability because it was too complex to read.
cf. #718 
In this PR, I refactored test cases of some methods in `AnnotateModels`.
I will refactor test cases of other methods in another PR.
> Refactor RSpec for AnnotateModels (1)

- lib/annotate/parser.rb
*   I replaced `#blank?` of ActiveSupport to `#present?`
*   I moved `AnnotateModels::Parser#commit` after `#parser ` because `#commit` is used after `#parser` in `#parse`.
> Refactor AnnotateModels::Parser

- lib/annotate/annotate_routes.rb
I refactored `AnnotateRoutes.annotate_routes` and `.rewrite_contents_with_header` in order to add an empty string to `new_content` array in `.annotate_routes`.
I will refactor `.rewrite_contents_with_header` more, and remove `. rewrite_contents_with_header` in the next PR.
> Refactor AnnotateRoutes.annotate_routes and .rewrite_contents_with_header

- .rubocop.yml
- lib/annotate/annotate_models.rb
- spec/lib/annotate/annotate_models_spec.rb
- spec/lib/annotate/parser_spec.rb
Globalize hooks into the model and removes the translated columns
from the `klass.columns`. This commit checks if globalize is
hooked into the model and adds the necessary columns to the
annotation array.
> Add columns managed by Globalize gem

- lib/annotate/annotate_routes.rb
I removed `AnnotateRoutes.rewrite_contents_with_header` because the logic of `AnnotateRoutes.rewrite_contents_with_header` is as same as `.rewrite_contents`.
> Remove AnnotateRoutes.rewrite_contents_with_header

- spec/lib/annotate/annotate_models_spec.rb
I refactored test cases of `AnnotateModels` with custom options.
> Refactor RSpec for AnnotateModels (3) - AnnotateModels.get_schema_info (with custom options)

- lib/annotate/annotate_routes.rb
I moved `puts` from `AnnotateRoutes.rewrite_contents` to `.do_annotations` and `.remove_annotations`.
> Refactor AnnotateRoutes.rewrite_contents

- lib/annotate/annotate_models.rb
As commented in #721, it seems like not all occurrences of the constants were renamed. This proposes a fix.
> Fix constant names that were not renamed in #721

- .rubocop_todo.yml
- Gemfile
- lib/annotate/annotate_models.rb
- lib/annotate/constants.rb
- lib/annotate/parser.rb
- lib/generators/annotate/templates/auto_annotate_models.rake
- lib/tasks/annotate_models.rake
- spec/integration/rails_4.1.1/lib/tasks/auto_annotate_models.rake
- spec/integration/rails_4.2.0/lib/tasks/auto_annotate_models.rake
- spec/lib/annotate/annotate_models_spec.rb
Hi,
The scope of this pull request is to allow annotate_models to generate models documentation using YARD. This is the first step, i'll add more features later.
> Support YARD notation

- spec/lib/annotate/annotate_models_spec.rb
I refactored test cases of AnnotateModels without custom options.
I will refactor the test case added in #602 in another PR.
> Refactor RSpec for AnnotateModels (4) - AnnotateModels.get_schema_info (without custom options)

- lib/annotate/annotate_routes.rb
- spec/lib/annotate/annotate_routes_spec.rb
I fixed message to make them more natural English.
> Fix messages from AnnotateRoutes

- lib/annotate/parser.rb
*   Removed unnecessary variables
*   Renamed variables that have same name as reserved word (`p`)
*   Other tiny fixes
> Refactor Annotate::Parser

- bin/annotate
Helper methods were moved into Annotate::Helpers but instances in bin/annotate had not been updated. Because of this, bin/annotate would throw NoMethodError.
> Fix bin/annotate NoMethodError

- spec/lib/annotate/annotate_models_spec.rb
Refactor test cases for AnnotateModels.get_schema_info with Globalize gem
> Refactor RSpec for AnnotateModels - with Globalize gem

- lib/annotate.rb
There is a bug where `additional_file_patterns` are not parsed as an array from the rake config.  This splits them by `,`, as the `parser.rb` for CLI args.
> Fix additional_file_patterns parsing

- lib/annotate/annotate_models.rb
- spec/lib/annotate/annotate_models_spec.rb
> Fix new lines after comments for rubocop compatibility

- lib/annotate/annotate_models.rb
- spec/integration/rails_5.2.4.1_spec.rb
- spec/integration/rails_6.0.2.1_spec.rb
- spec/lib/annotate/annotate_models_spec.rb
It was reported in https://github.com/ctran/annotate_models/issues/762 that column defaults were broken. This reverts changes made in #677 to restore the expected behavior of column defaults. 
For the time being columns with associated enums won't be working.
> [Revert #677] Fix column default annotations

- annotate.gemspec
In #764, it was pointed out that the gemspec requires ruby version `>= 2.2.0`. We've stopped testing for older versions of Ruby in CI and so it makes sense to make it explicit.
> Bump project required ruby version to >= 2.4

- .travis.yml
In https://travis-ci.org/github/ctran/annotate_models/builds/659982898/config?utm_medium=notification&utm_source=github_status it looks like `travis.yml` is not valid and seems the `matrix` portion seems to be overwriting `jobs`, which is used to release the gem. 
This config is valid. I used `travis lint .travis.yml` to validate locally.
> Make travis.yml valid and to unblock gem releases

- .travis.yml
- Gemfile
- spec/integration/integration_helper.rb
- spec/lib/annotate/annotate_models_spec.rb
- spec/spec_helper.rb
This PR does the following:
* moves code coverage generation to happen when `COVERAGE` environment variable is present.
* makes integration tests run when when `INTEGRATION_TESTS` is present.
* moves `ruby-head` from TravisCI build. Previously the configuration allowed for `ruby-head` to be ignored if it failed, but it conflicted with the gem release build job step.
> Some project clean up

- .github/workflows/ci.yml
- .travis.yml
Integration tests were made conditional in #786 and so they stopped running in CI. This PR adds the `INTEGRATION_TESTS` environment variable to CI so that integration tests start running again.
> Turn on integration tests in CI

- lib/annotate/annotate_models.rb
- spec/lib/annotate/annotate_models_spec.rb
I have some files in the "models" directory that are not true a `Class`. For example, a [`dry-types`](https://dry-rb.org/gems/dry-types/1.2/sum/) sum type:
```ruby
Foo = Types::String | Types::Integer
```
This results in the following line when I annotate.
```
Unable to annotate app/models/foo.rb: undefined method `<' for #<Dry::Struct::Sum:0x00007ff2dd262988>
```
Not a blocking issue but somewhat annoying nonetheless.
When annotating a file, check that the file's object is a `Class` to ensure it has the interface we expect.
> Fix "undefined method `<'" error message

- lib/annotate/annotate_models.rb
This is a bit of a cheat of a refactoring that simply extracts the logic for collecting a column's attributes out of `get_schema_info` and into its own method (`get_attributes`).
I found that in PRs like #779 that the Rubocop ABC limit was being exceeded:
```
lib/annotate/annotate_models.rb:235:5: C: Metrics/AbcSize: Assignment Branch Condition size for get_schema_info is too high. [145/145]
def get_schema_info(klass, header, options = {}) ...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Hopefully, this should break this up and reduce the complexity of the method.
There are opportunities to go further, but I thought this could be a good place to start. 
I would be open and interested in discussing further refactoring opportunities if it would make sense (maybe creating some new …
> Reactors AnnotateModels.get_schema_info

- lib/annotate/annotate_models.rb
- spec/lib/annotate/annotate_models_spec.rb
Closes #778 
If a column comment includes the newline character, the newline character
would be "printed" into the annotation block resulting in a line break
and an uncommented line.
For example, for the following table:
```
create_table "users", force: :cascade do |t|
t.string "name", comment: "This is a comment.\nWith two lines!"
t.datetime "created_at", precision: 6, null: false
t.datetime "updated_at", precision: 6, null: false
end
```
annotating the model with the `--with-comment` flag will result in:
```
\# == Schema Information
\#
\# Table name: users
\#
\#  id                                       :bigint           not null, primary key
\#  name(This is a comment.
With two lines!) :string
\#  created_at                               :datetime         not null
\#  updated_at …
```
> Fix output for multiline column comments

- annotate.gemspec
Allow people easier access the source code, raise issues and read the changelog, by adding [project metadata](https://guides.rubygems.org/specification-reference/#metadata) to the gemspec file.
These links will appear on the RubyGems page at https://rubygems.org/gems/annotate and be available via the RubyGems API – after the next release.
Also: used https in URLs.
> gemspec: Add metadata URIs

- lib/annotate/annotate_models.rb
- spec/lib/annotate/annotate_models_spec.rb
Currently the models annotator automatically attempts to find a class with a matching name at the bottom of project's directory tree before going up into specific engine's models.  This causes issues with models that share names with classes in other engines or lower classes in the project's directory.   This PR adds the option to skip attempts to load classes from lower directories and just uses the model's file path directly. 
#674 
cc @maxh
> Adding option to skip loading models from subdirectories

- lib/annotate/annotate_models/file_patterns.rb
- spec/lib/annotate/annotate_models/file_patterns_spec.rb
This is an addition to this PR: https://github.com/ctran/annotate_models/pull/692
I've seen it's been stale for a while and it's rather simple fix.
I noticed my ActiveAdmin resources are not being annotated.
I know ActiveAdmin uses plural model names, but, as far as I remember, they used to use singular model names in the past.
We can see some "evidence" of that here: https://activeadmin.info/2-resource-customization.html#customizing-parent-menu-items
Probably in other places as well.
In order to keep the gem working as expected for singular ActiveAdmin resources, I suggest we annotate both singular and plural model names.
I just tested this out in a project of mine where I renamed one file to be in singular form and left the other files in plural form.
It worked like a charm. :)
I also …
> ActiveAdmin: Allow for both singular and plural model names

- lib/tasks/annotate_models_migrate.rake
- spec/integration/rails_6.0.2.1/config/application.rb
- spec/integration/rails_6.0.2.1/config/multi-database.yml
- spec/integration/rails_6.0.2.1_spec.rb
Rails 6 adds a new set of migration tasks for multi-database apps. This change makes the annotate_models_migrate hooks aware of them.
This change was a little awkward to test, but I'm happy to change my approach/use a dummy app for more robust integration tests if desired.
> Add annotation hooks for db-specific migration tasks

- lib/tasks/annotate_routes.rake
Make `annotate_routes` depend on `set_annotation_options` just as `annotate_models` does.
Fixes #761.
I copied the `ENV['is_cli']` check from `annotate_models.rake`, but I don't know what its purpose is. Feel free to tell me to get rid of it. I also moved the `annotate_lib = ...` bit to the top of the file to keep `annotate_routes.rake` consistent with `annotate_models.rake`.
> load :set_annotation_options before running :annotate_routes

- README.md
- lib/annotate/annotate_models.rb
- spec/lib/annotate/annotate_models_spec.rb
This is a bugfix for the following case:
```
module Foo; end
class Bar::Foo < Activerecord::Base; end
```
Where `Bar::Foo` would never get annotated.
> Only return valid models from get_loaded_model_by_path

- lib/tasks/annotate_models_migrate.rake
ActiveRecord's migrate tasks are required since v2.7.5 (#588).
1. create non-rails project (like sinatra)
```
./
├── app.rb
├── Gemfile
├── Gemfile.lock
└── models/
└── user.rb
```
```ruby
source "https://rubygems.org"
gem "activerecord", require: "active_record"
gem "annotate"
gem "sqlite3"
```
```ruby
Bundler.require(:default)
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Schema.define do
create_table :users, force: true do |t|
end
end
Dir["models/*.rb"].sort.each {|f| require_relative f }
```
```ruby
class User < ActiveRecord::Base
end
```
2. execute annotate
```sh
$ bundle exec annotate -R ./app.rb --models --model-dir models
```
```sh
$ bundle exec annotate -R ./app.rb --models --model-dir models
-- create_table(:users, …
```
> Fix: RuntimeError: Don't know how to build task 'db:migrate'

- spec/lib/annotate/annotate_models_spec.rb
This PR fixes a typo in a  test name.
> Fix typo invlaid -> invalid

- lib/annotate/annotate_models.rb
This commit partially reverts #801, which by declaring conditional return
has turned `get_loaded_model_by_path` to a less safe method that can
return nil when its condition is not met.
Apparently the very same condition has been brought to `annotate_model_file`
by #774, which seems to cover the "bug" insisted in #801 as well.
On the other hand #801 has brought an inconvenient behaviour as well:
whenever a non-activerecord model file is found, `get_loaded_model_by_path`
returns nil, which leads to raising `BadModelFileError` and ends up
printing a bunch of "Unable to annotate ..." messages.
Now it seems tests added by #801 are running right and I do not find
a problem restoring the previous behaviour and turn it nil-safe again.
---
Say we have a file like `app/models/foo/bar.rb` which is …
> `get_loaded_model_by_path` is supposed to be nil-safe

- lib/annotate/annotate_models.rb
- spec/lib/annotate/annotate_models_spec.rb
Hi,
In a middle of a refactoring task, we came across a issue with globalize + annotate. Annotate is adding a none-existant field to the model:
```git
#
+ #  country_id  :integer
....
``` 
The issue come when you overide `table_name`. For exemple, if we have a model `Country` located at `models/country.rb` and we decide to move the file in a folder without changing the table_name, we will have:
`models/folder/country.rb`
```ruby
module Folder
class Country < ApplicationRecord
self.table_name = "countries"
...
end
end
#
#
```
With the orginal code, we have:
```ruby
pry(main)> klass = Folder::Country
pry(main)> foreign_column_name = [klass.translation_class.to_s.gsub('::Translation', '').gsub('::', '_').downcase,'_id'].join.to_sym
=> :folder_country_id
```
Using table_name is a safer way to …
> Fix: use klass.table_name instead of guessing from associated models

- lib/annotate/annotate_models.rb
- spec/lib/annotate/annotate_models_spec.rb
Fix undefined method error when spatial column does not have `srid`. This error occurs when the following gem is used.
https://github.com/sebastianiorga/activerecord-mysql2spatial-adapter
(forked from https://github.com/rgeo/activerecord-mysql2spatial-adapter)
```
Unable to annotate app/models/location.rb: undefined method `srid' for #<ActiveRecord::ConnectionAdapters::Mysql2SpatialAdapter::SpatialColumn:...
```
> Fix undefined method error when spatial column does not have `srid`

- annotate.gemspec
- lib/tasks/annotate_routes.rake
- spec/integration/rails_5.2.4.1/Gemfile.lock
- spec/integration/rails_6.0.2.1/Gemfile
- spec/integration/rails_6.0.2.1/Gemfile.lock
This change allows the gem to work with Rails 7 now that it's out.
I've been using it for a while with alpha and RC versions and at least models and routes work fine.
EDIT:
~~Just included as a bonus a `rake routes` task that fixes the problems that showed up when rails renamed the task to `rails routes`~~
> Loosen activerecord restriction to work with rails 7

- lib/annotate/annotate_models.rb
- spec/lib/annotate/annotate_models_spec.rb
Some tables may have a table_name_prefix but no indexes. Previous versions of
the code would strip the prefix and look for indexes on the resulting table name,
which likely would not exist. This causes DB errors, at least in MySQL. So now
check if the table with the derived name exists first before trying to show its indexes.
Example error otherwise:
```
myservice:development [10] pry(main)> ActiveRecord::Base.connection.indexes('garbage')
Mysql2::Error: Table 'myservice_development.garbage' doesn't exist: SHOW KEYS FROM `garbage`
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'myservice_development.garbage' doesn't exist: SHOW KEYS FROM `garbage`
```
> Fix retrieve_indexes_from_table when indexes is empty and base table does not exist

- lib/annotate/annotate_models.rb
This PR fixes these errors due to the presence of `# frozen_string_literal: true` in files :
```sh
Unable to annotate app/models/camping.rb: can't modify frozen String: "decimal"
/home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:875:in `get_attributes'
/home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:151:in `block in get_schema_info'
/home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:149:in `each'
/home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:149:in …
```
> Fix error: can't modify frozen String: "decimal"
